// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpoqnmmnchjvssjkoydj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwb3FubW1uY2hqdnNzamtveWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTA0MDAsImV4cCI6MjA2NjUyNjQwMH0.ov-Mxzz13q1IxWjtyVlM2G8b-JNcOfssFljWifzZAag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);